<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{4f7f124e-2b6e-4c71-87e2-245c0f9c49a6}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	myEnum : (MY_THIS,MY_THAT);
	myDutEnum : MY_DUT_ENUM;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>